### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by eldinor** [RolandCsibrei/babylonjs-console3#1]
Here is what I've got after `tsc .\src\console3.ts`
![image](https://user-images.githubusercontent.com/25833327/143624674-667422d4-cfa2-4398-9727-d7616414d7f8.png)

`node .\src\topg.js` - seems to work; at least I found the file `console3-playground.js `file in the src folder (didn't check if it works).

**Comment by RolandCsibrei** [comment]
This was working and I am still investigating what causes this issue. It might be the tsc version. However it compiles and creates the output js file.

**Comment by RolandCsibrei** [comment]
tsc version 4.4+ is needed to compile the project. Tested on 4.5.2.
